### ISSUE TITLE
Type definition is broken by incorrect UI5 Documentation

### ISSUE THREAD

**Issue by lucasheim** [ui5-next/types#3] opened 2019-10-01 13:39 UTC
In sap.ui.core, there's a documentation error that causes the definition to break:

![image](https://user-images.githubusercontent.com/13325346/65967228-a4c1a880-e437-11e9-9ce5-6f3347cabf0a.png)

![image](https://user-images.githubusercontent.com/13325346/65967273-b3a85b00-e437-11e9-9a67-3127d3e1c993.png)

Is there a way to treat this special case?

**Comment by Soontao** [comment] 2019-10-01 13:57
Yes, this case should be fixed in definition generator. 

In fact, there are many fixed exceptions in definition code, the root cause is that the are 
many misspellings in the original jsdoc written by ui5 developers.

If you are anxious, you can try to fix it [here](https://github.com/ui5-next/types/blob/7095c0b128e0c00c04483b837065e807d190a2ce/builder/formatter.ts#L113). If not, I'll fix it tomorrow.

https://github.com/ui5-next/types/blob/7095c0b128e0c00c04483b837065e807d190a2ce/builder/formatter.ts#L113

**Comment by lucasheim** [comment] 2019-10-01 18:47
I've tried using the part of the code you highlighted, but that is only for parameter/return types, not for parameter names. I'm looking into alternatives.

**Comment by Soontao** [comment] 2019-10-02 00:44
Fixed by #6

**Comment by Soontao** [comment] 2019-10-02 01:22
Version v1.4.1 released

**Closed as completed** 2019-10-02 01:29 UTC
Labels: bug
